//
//  Created by Maciej Gomółka on 17.06.23.
//

enum Random {

    static func flashcardsSet() -> FlashcardsSet {
        let numberOfFlashcards = (0...50).randomElement()!
        return .init(name: "\(word()) set", flashcards: flashcards(numberOfFlashcards))
    }

    static func flashcards(_ number: Int) -> [Flashcard] {
        (0..<number).map { _ in .init(front: word(), back: word()) }
    }

    static func word() -> String {
        [
            "fireman",
            "support",
            "heal",
            "fix",
            "behavior",
            "fuzzy",
            "miss",
            "name",
            "versed",
            "spade",
            "longing",
            "elastic",
            "destruction",
            "combative",
            "hungry",
            "tramp",
            "illustrious",
            "airport",
            "cow",
            "judge",
            "cup",
            "hurt",
            "manage",
            "observe",
            "tickle",
            "cautious",
            "icky",
            "overjoyed",
            "voracious",
            "deeply",
            "prickly",
            "incompetent",
            "big",
            "volleyball",
            "fog",
            "vigorous",
            "system",
            "title",
            "friends",
            "untidy",
            "horse",
            "cat",
            "dime",
            "depressed",
            "oven",
            "embarrassed",
            "actor",
            "guttural",
            "marble",
            "disgusting",
            "account",
            "uneven",
            "hill",
            "materialistic",
            "groan",
            "fish",
            "crowded",
            "trashy",
            "reproduce",
            "sound",
            "program",
            "nostalgic",
            "magic",
            "deceive",
            "load",
            "unsightly",
            "wren",
            "loss",
            "eye",
            "pigs",
            "badge",
            "tearful",
            "curly",
            "capable",
            "crayon",
            "ultra",
            "jellyfish",
            "squash",
            "argue",
            "rotten",
            "afterthought",
            "mark",
            "want",
            "order",
            "team",
            "pear",
            "perfect",
            "skip",
            "force",
            "divergent",
            "mess up",
            "curvy",
            "interfere",
            "rainy",
            "numerous",
            "last",
            "resonant",
            "snobbish",
            "heartbreaking",
            "silent"
        ].randomElement()!
    }

}
